- pyproject.toml
> chore: v0.1.1

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- pyproject.toml
> fix(ci/release): Fix wheels path

- src/core.rs
> feat: allow to read xls, xlsx, xlsb... automatically

- .github/workflows/CI.yml
- Makefile
- README.md
- prod_install.sh
> docs: Updated dev documentation and added a Makefile

- python/fastexcel/__init__.py
> fix(python): Forward __repr__ methods to wrapper classes

- src/utils/arrow.rs
> feat(rust/utils/arrow): Provide a default name for unnamed columns

- src/types/excelsheet.rs
> fix(rust/ExcelSheet): Subtract 1 from the height to avoid counting the header

- Cargo.lock
- Cargo.toml
- src/types/excelsheet.rs
- src/utils/arrow.rs
> feat(rust): Add support for DateTimes

- Cargo.lock
- Cargo.toml
- src/types/excelreader.rs
> chore(deps): bump calamine 0.18.0 -> 0.19.1

- python/tests/test_fastexcel.py
- src/types/excelreader.rs
- src/types/excelsheet.rs
- src/utils/arrow.rs
> refactor(types/ExcelSheet): Stop bearing a reference to an arrow schema

- .github/workflows/release.yml
> feat(CI/release): Auto-generate release notes

- Cargo.lock
- Cargo.toml
> chore: v0.2.0

- Cargo.lock
- Cargo.toml
> chore: v0.2.1

- python/fastexcel/__init__.py
- python/fastexcel/_fastexcel.pyi
- python/tests/test_fastexcel.py
- src/types/excelreader.rs
- src/types/excelsheet.rs
- src/utils/arrow.rs
Add the skip_rows and n_rows capability
> Pagination

- Cargo.lock
- Cargo.toml
> chore: v0.3.0

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
> fix: typo in release action

- .github/workflows/docs.yml
> feat(docs): Added an automatic doc build job

- .github/workflows/docs.yml
> fix(ci/docs): Install missing dependencies

- .github/workflows/docs.yml
> fix(ci/docs): Create a venv for maturin

- src/types/excelreader.rs
> fix: change legacy [args] macros

- Cargo.lock
- Cargo.toml
- src/types/excelsheet.rs
- src/utils/arrow.rs
Simplification of the changes introduced by #74 :slightly_smiling_face: 
Memory profile still looks good
> refactor(ffi): Simplify FFI usage

- python/fastexcel/__init__.py
Fixes changes introduced by #87
> fix: Ensure the lib can be used without the polars extra

- .gitignore
- python/fastexcel/__init__.py
- python/fastexcel/_fastexcel.pyi
- python/tests/test_errors.py
- python/tests/test_fastexcel.py
- src/lib.rs
- src/types/excelreader.rs
> feat: read excel from bytes content

- Makefile
Adapt to new ruff params after bump done in #194
> fix(make): adapt to ruff 0.3.0

- .github/workflows/release.yml
> ci(release): also build arm64 wheels

- python/tests/test_column_selection.py
- python/tests/test_use_columns.py
- src/types/python/excelsheet/column_info.rs
- src/types/python/excelsheet/mod.rs
> fix(excelsheet): `column_names` should work with `use_columns`

- python/tests/test_column_selection.py
- src/types/python/excelreader.rs
> fix: take use_columns into account when loading a sheet eagerly

- python/fastexcel/__init__.py
closes https://github.com/ToucanToco/fastexcel/issues/255
> docs: tweak `header_row` and `skip_rows` description

- .github/workflows/CI.yml
- .github/workflows/release.yml
> fix(ci): bump macos runners to 14 and explcitly specify targets on macos

- python/fastexcel/__init__.py
- python/fastexcel/_fastexcel.pyi
- python/tests/test_tables.py
- src/data.rs
- src/lib.rs
- src/types/python/excelreader.rs
- src/types/python/excelsheet/column_info.rs
- src/types/python/excelsheet/mod.rs
- src/types/python/excelsheet/sheet_data.rs
- src/types/python/mod.rs
- src/types/python/table.rs
- test-requirements.txt
> feat: introduce ExcelTable object

- python/fastexcel/__init__.py
- python/tests/test_errors.py
- src/types/python/excelreader.rs
> feat: forbid schema_sample_rows=0

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
> chore: v0.14.0

- python/fastexcel/__init__.py
- python/tests/benchmarks/memory.py
- python/tests/benchmarks/readers.py
- python/tests/benchmarks/speed.py
Because `pyright` is very common, integrated with zed and vscode
> chore: make both mypy and pyright happy

- .github/workflows/CI.yml
- .github/workflows/release.yml
> build: fix wheel build options
