Cargo.lock, Cargo.toml
This release officially adds support for Python 3.11
=> chore(deps): Bump pyo3 0.17.2 -> 0.17.3

Cargo.lock, Cargo.toml
Bumping a release after adding support for Python 3.11
=> chore: v0.4.1

Cargo.lock, Cargo.toml, python/fastexcel/__init__.py, python/fastexcel/_fastexcel.pyi, src/types/excelreader.rs, src/types/excelsheet.rs, src/utils/arrow.rs
Was lurking the web and found this reddit post https://www.reddit.com/r/rust/comments/qy5arf/how_to_pass_dataframes_between_rust_and_python/
I tried to replicate it. After adapting to rs-arrow i got this memory usage plot.
With pybytes with a WriteStream : 
With a c_ffi implementation : 
Data seem's ok so far. Maybe need to have a closer look
=> Using C FFI for interop rust -> Python

.github/workflows/CI.yml, .github/workflows/release.yml, .gitignore, README.md, pyproject.toml, python/fastexcel/__init__.py, python/fastexcel/_fastexcel.pyi, python/tests/benchmarks/memory.py, python/tests/test_durations.py, python/tests/test_empty.py, python/tests/test_fastexcel.py
Hoping that a patch to extend Python support is welcome :wink:  
I was looking to integrate a `calamine` based Excel parser as one of our supported engines in the Polars `read_excel` method (I am one of the core devs for that project), but we need to support Python versions >= 3.8. While we could potentially have `python_calamine` handle earlier versions, I'm reluctant to do so as `fastexcel` is much better-suited for our use-case and benchmarks significantly faster (producing Arrow data without materialising anything in Python-space; nicely done!)
Took a look at the code to see if it could be extended to cover the earlier versions, and it seems like a straightforward low-impact update; I've validated that everything compiles/runs on the earlier Python versions (testing on x86 Ubuntu …
=> feat: extend `fastexcel` support to python >= 3.8

.github/workflows/CI.yml, .github/workflows/release.yml, Makefile, pyproject.toml
=> feat: Add windows support 

python/fastexcel/__init__.py
Minor quality of life update; allows for transparent use of paths that include the user dir shortcut, eg:
```python
from fastexcel import read_excel
xl = read_excel("~/files/test.xlsx")
```
=> feat: allow spreadsheet location to include user directory shortcut `~`

.github/workflows/CI.yml, .github/workflows/release.yml, Cargo.toml
This simplifies our wheel build process by using the abi3 API.
https://pyo3.rs/v0.14.5/building_and_distribution#py_limited_apiabi3
It allows us to build only a single wheel per target OS/arch.
closes #168
=> feat(build): build abi3 wheels

.github/dependabot.yml, Cargo.lock, Cargo.toml, src/types/excelsheet.rs
Since arrow and pyo3 both depend on a specific version of pyo3-ffi, seems like dependabot was not able to update them independently
Added dependabot groups for cargo deps to try to solve this issue
Also set the right labels (those with emoji) because it irritates me to have duplicate labels :smile:
=> fix(deps): update calamine and pyo3

python/fastexcel/__init__.py, python/fastexcel/_fastexcel.pyi, python/tests/test_column_selection.py, src/types/excelreader.rs, src/types/excelsheet.rs
As discussed, follow-up of #189
=> feat: support column ranges in string format in use_columns 

python/fastexcel/__init__.py, python/fastexcel/_fastexcel.pyi, python/tests/test_dtypes.py, src/types/dtype.rs, src/types/excelreader.rs, src/types/excelsheet.rs, src/types/mod.rs, src/utils/arrow.rs
=> feat: added support for a dtypes parameter 

python/tests/test_errors.py, src/types/python/excelreader.rs
=> fix: raise `SheetNotFoundError` when reading a missing sheet name

pyproject.toml, python/fastexcel/__init__.py
This PR incorporates `typing-extensions` into `fastexcel`'s dependencies, addressing Issue #226.
This update resolves a subtle bug in the `polars` library's `read_excel` function, specifically when utilizing the `calamine` engine.
Before this change, attempting to use the `calamine` engine would trigger an erroneous message from `polars`, indicating that `fastexcel` was not installed, despite its presence. This issue stemmed from the absence of the `typing-extensions` dependency.
All test are passing after running `make test`.
=> fix: add `typing-extensions` to dependencies

Cargo.lock, Cargo.toml, pyproject.toml, src/lib.rs, src/types/dtype.rs, src/types/idx_or_name.rs, src/types/python/excelreader.rs, src/types/python/excelsheet/mod.rs
This bumps pyo3 to v0.21, which introduces a new API: 
* https://pyo3.rs/v0.21.2/migration#from-020-to-021
* https://polar.sh/davidhewitt/posts/replacing-pyo3-api-pt1
=> chore(deps): bump pyo3 0.20.3 -> 0.21.2 

python/tests/conftest.py, python/tests/test_column_selection.py, python/tests/test_fastexcel.py, src/types/python/excelreader.rs, src/types/python/excelsheet/column_info.rs, src/types/python/excelsheet/mod.rs
Fix an inconsistency in column ordering when loading a sheet eagerly. I guess this occured because the ager loading PR stood open for so long that the refactoring on column metadata was done in the meantime, and wasn't properly taken into account when updating the eagerness branch
=> fix: respect provided column ordering in use_columns when loading a sheet eagerly

.github/workflows/CI.yml, .github/workflows/release.yml
weirdly, maturin interprets `python3.8` as `pypy` on macos. Without specifying the interpreter, we get an ABI3 wheel, as expected
=> fix(ci): fix interpreter used by maturin

Cargo.toml, pyproject.toml
=> build: add license and other stuff

python/fastexcel/__init__.py, python/fastexcel/_fastexcel.pyi, python/tests/test_dtypes.py, src/types/dtype.rs, src/types/python/excelreader.rs, src/types/python/excelsheet/column_info.rs, src/types/python/excelsheet/mod.rs, src/types/python/table.rs
to merge after #298
closes #257
Now you can load a sheet with `dtypes = "string"` directly to set one dtype for all columns
=> feat: add support for one dtype for all columns

python/fastexcel/__init__.py, python/fastexcel/_fastexcel.pyi, python/tests/test_alias_generation.py, python/tests/test_column_selection.py, python/tests/test_dtypes.py, python/tests/test_tables.py, src/data.rs, src/error.rs, src/lib.rs, src/types/python/excelreader.rs, src/types/python/excelsheet/column_info.rs, src/types/python/excelsheet/mod.rs, src/types/python/table.rs
This changes our logic regarding the information we extract on sheet load. Rather than loading dtype information for all available columns, we only load it for selected columns. This introduces two breaking changes:
* For `ExcelTable` and `ExcelSheet`, `available_columns`  is no longer a property. It is now a method, and information regarding available columns is computed on-demand (the information is cached after having been computed once).
* If `use_columns` is a callable, it no longer receives a `ColumnInfo` object, but a `ColumnInfoBuilder` instead (no dtype information).
* `ColumnInfoBuilder` is now part of the Python API.
@PrettyWood If you have a better naming suggestion for `ColumnInfoBuilder`, I'd love to hear it.  Maybe `ColumnNameInfo` or `ColumnInfoNoDtype` ?
closes #327
=> feat!(excelreader): only load dtypes for columns specified via `use_columns`

Cargo.lock, Cargo.toml, src/arrow_capsule.rs, src/data.rs, src/types/dtype.rs, src/types/python/excelreader.rs, src/types/python/excelsheet/column_info.rs, src/types/python/excelsheet/mod.rs, src/types/python/table.rs
The repo currently brings in all of the default features of the `arrow` crate. We can have faster compile times by only bringing in the relevant sub-crates.
=> Use split arrow crates for smaller dependency footprint

Cargo.lock, Cargo.toml
This is implemented on top of #362 and that should be merged first.
=> chore(deps): bump arrow to 56.1.0 and pyo3 to 0.25.1

.github/workflows/CI.yml, .github/workflows/release.yml, Makefile, pyproject.toml
Specify all maturin specific features in pyproject.toml instead of cli arguments.
It simplifies deployment. It also makes conda package deployment simpler.
=> build: Specify all maturin features in pyproject.toml
